service: serverless-step-functions-example

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action: dynamodb:*
      Resource: !GetAtt BooksTable.Arn
    - Effect: Allow
      Action: dynamodb:*
      Resource: !GetAtt UsersTable.Arn

plugins:
  - serverless-step-functions

functions:
  checkInventory:
    handler: handler.checkInventory
  calculateTotal:
    handler: handler.calculateTotal
  redeemPoints:
    handler: handler.redeemPoints
  billCustomer:
    handler: handler.billCustomer

stepFunctions:
  stateMachines:
    checkoutStoreFlow:
      name: checkoutStoreFlow
      definition:
        StartAt: checkInvntory
        States:
          checkInvntory:
            Type: Task
            Resource:
              Fn::GetAtt: [checkInventory, Arn]
            Next: calculateTotal
            Catch:
              - ErrorEquals: [BookOutOfStock]
                Next: BookOutOfStockError
              - ErrorEquals: [BookNotFound]
                Next: BookNotFoundError
            ResultPath: $.book
          calculateTotal:
            Type: Task
            Resource:
              Fn::GetAtt: [calculateTotal, Arn]
            ResultPath: $.total
            Next: IsRedeemNeeded
          IsRedeemNeeded:
            Type: Choice
            Choices:
              - Variable: $.redeem
                BooleanEquals: true
                Next: RedeemPoionts
            Default: BillCustomer
          RedeemPoionts:
            Type: Task
            Resource:
              Fn::GetAtt: [redeemPoints, Arn]
            Next: BillCustomer
          BillCustomer:
            Type: Task
            Resource:
              Fn::GetAtt: [billCustomer, Arn]
            Next: prepareOrder
          BookOutOfStockError:
            Type: Pass
            Result: "Book is out of stock"
            End: true
          BookNotFoundError:
            Type: Pass
            Result: "Book not found/"
            End: true

resources:
  Resources:
    BooksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: bookId
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: bookId
            AttributeType: S
        TableName: stepfunction-books
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        TableName: stepfunction-users
      